risk.control.system/Controllers/UploadsController.cs
using System.Data;
using System.Text.RegularExpressions;

using Microsoft.AspNetCore.Mvc;

using risk.control.system.Models.ViewModel;

namespace risk.control.system.Controllers
{
    public class UploadsController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        private static string NO_DATA = " NO - DATA ";
        private static Regex regex = new Regex("\\\"(.*?)\\\"");

        public UploadsController(IWebHostEnvironment webHostEnvironment)
        {
            this.webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormFile postedFile)
        {
            if (postedFile != null)
            {
                string path = Path.Combine(webHostEnvironment.WebRootPath, "upload-case");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string fileName = Path.GetFileName(postedFile.FileName);
                string filePath = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                }

                string csvData = await System.IO.File.ReadAllTextAsync(filePath);
                DataTable dt = new DataTable();
                bool firstRow = true;
                foreach (string row in csvData.Split('\n'))
                {
                    if (!string.IsNullOrEmpty(row))
                    {
                        if (!string.IsNullOrEmpty(row))
                        {
                            if (firstRow)
                            {
                                foreach (string cell in row.Split(','))
                                {
                                    dt.Columns.Add(cell.Trim());
                                }
                                firstRow = false;
                            }
                            else
                            {
                                dt.Rows.Add();
                                int i = 0;
                                var output = regex.Replace(row, m => m.Value.Replace(',', '@'));
                                var rowData = output.Split(',').ToList();
                                foreach (string cell in rowData)
                                {
                                    dt.Rows[dt.Rows.Count - 1][i] = cell?.Trim() ?? NO_DATA;
                                    i++;
                                }
                            }
                        }
                    }
                }

                return View(dt);
            }
            return Problem();
        }
    }
}

risk.control.system/Views/Uploads/Index.cshtml
@using System.Data;
@model DataTable

@{
    ViewData["Title"] = Applicationsettings.UPLOAD;
}

<section class="content">
    <div class="container-fluid">

        <form asp-controller="Uploads" asp-action="Index" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">@Applicationsettings.UPLOAD</h3>
                    </div>
                    <div class="card-body dataTable-search-form">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="file" name="postedFile" required />
                                    <input type="text" autocomplete="off" placeholder="Enter File Description" name="description" required />
                                        <button type="submit" class="btn btn-danger" asp-controller="Uploads" asp-action="Index"><i class="nav-icon fa fa-upload"></i> @Applicationsettings.RECORD</button>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">@Applicationsettings.UPLOADED_SAMPLE</h3>
                        </div>
                        <div class="card-body contained-width">
                            @if (Model!= null)
                            {
                                <hr />
                                <table class="table table-striped  fixed-with-height">
                                    <tr>
                                        @foreach (DataColumn dc in Model.Columns)
                                        {
                                            <th>@dc.ColumnName</th>
                                        }
                                    </tr>
                                    @foreach (DataRow dr in Model.Rows)
                                    {
                                        <tr>
                                            @foreach (DataColumn dc in Model.Columns)
                                            {
                                                <td>@dr[dc.ColumnName]</td>
                                            }
                                        </tr>
                                    }
                                </table>
                            }
                            else
                            {
                                <caption>@Applicationsettings.NO_RECORDS_FOUND</caption>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>