risk.control.system/Models/InvestigationCase.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace risk.control.system.Models
{
    public class InvestigationCase : BaseEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string InvestigationId { get; set; } = Guid.NewGuid().ToString();
        public string Name { get; set; } = default!;
        public string Description { get; set; } = default!;
        [Display(Name = "Line of Business")]
        public string? LineOfBusinessId { get; set; } = default!;
        [Display(Name = "Line of Business")]
        public LineOfBusiness? LineOfBusiness { get; set; } = default!;
        public string? InvestigationServiceTypeId { get; set; } = default!;
        public InvestigationServiceType? InvestigationServiceType { get; set; } = default!;
        [Display(Name = "Case status")]
        public string? InvestigationCaseStatusId { get; set; } = default!;
        [Display(Name = "Case status")]
        public InvestigationCaseStatus? InvestigationCaseStatus { get; set; } = default!;
    }

}

risk.control.system/Controllers/InvestigationCaseController.cs
using System.Data;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using NToastNotify;

using risk.control.system.Data;
using risk.control.system.Models;

using SmartBreadcrumbs.Attributes;

namespace risk.control.system.Controllers
{
    [Breadcrumb("Case")]
    public class InvestigationCaseController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification toastNotification;
        private readonly IWebHostEnvironment webHostEnvironment;

        public InvestigationCaseController(ApplicationDbContext context, IToastNotification toastNotification, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.toastNotification = toastNotification;
            this.webHostEnvironment = webHostEnvironment;
        }

        // GET: RiskCases
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? currentPage, int pageSize = 10)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                currentPage = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var cases = _context.InvestigationCase.Include(r => r.InvestigationCaseStatus).Include(r => r.LineOfBusiness).AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                cases = cases.Where(s =>
                 s.Name.ToLower().Contains(searchString.Trim().ToLower()) ||
                 s.InvestigationCaseStatus.Name.ToLower().Contains(searchString.Trim().ToLower()) ||
                 s.InvestigationCaseStatus.Code.ToLower().Contains(searchString.Trim().ToLower()) ||
                 s.LineOfBusiness.Name.ToLower().Contains(searchString.Trim().ToLower()) ||
                 s.LineOfBusiness.Code.ToLower().Contains(searchString.Trim().ToLower()) ||
                 s.Description.ToLower().Contains(searchString.Trim().ToLower())
                 );
            }
            switch (sortOrder)
            {
                case "name_desc":
                    cases = cases.OrderByDescending(s => s.Name);
                    break;

                case "Date":
                    cases = cases.OrderBy(s => s.Created);
                    break;

                case "date_desc":
                    cases = cases.OrderByDescending(s => s.Created);
                    break;

                default:
                    cases = cases.OrderBy(s => s.Created);
                    break;
            }

            int pageNumber = (currentPage ?? 1);
            ViewBag.TotalPages = (int)Math.Ceiling(decimal.Divide(cases.Count(), pageSize));
            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.ShowPrevious = pageNumber > 1;
            ViewBag.ShowNext = pageNumber < (int)Math.Ceiling(decimal.Divide(cases.Count(), pageSize));
            ViewBag.ShowFirst = pageNumber != 1;
            ViewBag.ShowLast = pageNumber != (int)Math.Ceiling(decimal.Divide(cases.Count(), pageSize));

            var caseResult = await cases.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToListAsync();
            return View(caseResult);
        }

        // GET: RiskCases/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.InvestigationCase == null)
            {
                return NotFound();
            }

            var investigationCase = await _context.InvestigationCase
                .Include(r => r.InvestigationCaseStatus)
                .Include(r => r.LineOfBusiness)
                .FirstOrDefaultAsync(m => m.InvestigationId == id);
            if (investigationCase == null)
            {
                return NotFound();
            }

            return View(investigationCase);
        }

        // GET: RiskCases/Create
        [Breadcrumb("Add Case")]
        public IActionResult Create()
        {
            ViewBag.InvestigationCaseStatusId = new SelectList(_context.InvestigationCaseStatus, "InvestigationCaseStatusId", "Name");
            ViewBag.LineOfBusinessId = new SelectList(_context.LineOfBusiness, "LineOfBusinessId", "Name");
            return View();
        }

        // POST: RiskCases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(InvestigationCase investigationCase)
        {
            _context.Add(investigationCase);
            await _context.SaveChangesAsync();
            toastNotification.AddSuccessToastMessage("case created successfully!");
            return RedirectToAction(nameof(Index));
        }

        // GET: RiskCases/Edit/5
        [Breadcrumb("Edit Case")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.InvestigationCase == null)
            {
                toastNotification.AddErrorToastMessage("case not found!");
                return NotFound();
            }

            var investigationCase = await _context.InvestigationCase.FindAsync(id);
            if (investigationCase == null)
            {
                toastNotification.AddErrorToastMessage("case not found!");
                return NotFound();
            }
            ViewBag.InvestigationCaseStatusId = new SelectList(_context.InvestigationCaseStatus, "InvestigationCaseStatusId", "Name", investigationCase.InvestigationCaseStatusId);
            ViewBag.LineOfBusinessId = new SelectList(_context.LineOfBusiness, "LineOfBusinessId", "Name", investigationCase.LineOfBusinessId);
            return View(investigationCase);
        }

        // POST: RiskCases/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, InvestigationCase investigationCase)
        {
            if (id != investigationCase.InvestigationId)
            {
                toastNotification.AddErrorToastMessage("case not found!");
                return NotFound();
            }

            try
            {
                _context.Update(investigationCase);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!InvestigationCaseExists(investigationCase.InvestigationId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            toastNotification.AddSuccessToastMessage("district edited successfully!");
            return RedirectToAction(nameof(Index));
        }

        // GET: RiskCases/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.InvestigationCase == null)
            {
                toastNotification.AddErrorToastMessage("case not found!");
                return NotFound();
            }

            var investigationCase = await _context.InvestigationCase
                .Include(r => r.InvestigationCaseStatus)
                .Include(r => r.LineOfBusiness)
                .FirstOrDefaultAsync(m => m.InvestigationId == id);
            if (investigationCase == null)
            {
                toastNotification.AddErrorToastMessage("case not found!");
                return NotFound();
            }

            return View(investigationCase);
        }

        // POST: RiskCases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.InvestigationCase == null)
            {
                toastNotification.AddErrorToastMessage("case not found!");
                return Problem("Entity set 'ApplicationDbContext.RiskCase'  is null.");
            }
            var investigationCase = await _context.InvestigationCase.FindAsync(id);
            if (investigationCase != null)
            {
                _context.InvestigationCase.Remove(investigationCase);
            }

            await _context.SaveChangesAsync();
            toastNotification.AddSuccessToastMessage("district deleted successfully!");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile postedFile)
        {
            if (postedFile != null)
            {
                string path = Path.Combine(webHostEnvironment.WebRootPath, "upload-cases");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string fileName = Path.GetFileName(postedFile.FileName);
                string filePath = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                }
                string csvData = await System.IO.File.ReadAllTextAsync(filePath);
                DataTable dt = new DataTable();
                bool firstRow = true;
                foreach (string row in csvData.Split('\n'))
                {
                    if (!string.IsNullOrEmpty(row))
                    {

risk.control.system/Views/InvestigationCase/Create.cshtml
@model risk.control.system.Models.InvestigationCase

@{
    ViewData["Title"] = "Create";
}
<section class="content pt-2">
    <div class="container-fluid ">
        <form id="create-form" asp-action="Create" asp-antiforgery="true">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Create Case</h3>
                        </div>
                        <div class="card-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="LineOfBusinessId" class="control-label"></label>
                                <select asp-for="LineOfBusinessId" class="form-control"
                                        asp-items="ViewBag.LineOfBusinessId">
                                    <option>--- SELECT LINE OF BUSINESS ---</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="InvestigationCaseStatusId" class="control-label"></label>
                                <select asp-for="InvestigationCaseStatusId" class="form-control"
                                        asp-items="ViewBag.InvestigationCaseStatusId">
                                    <option>--- SELECT CASE STATUS ---</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Created" class="control-label"></label>
                                <input asp-for="Created" class="form-control" />
                                <span asp-validation-for="Created" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputFile">File input</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="exampleInputFile">
                                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                    </div>
                                    <div class="input-group-append">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">...</h3>
                        </div>
                        <div class="card-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <button disabled=true type="button" class="btn btn-secondary">___User name</button>
                                </div>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="LineOfBusinessId" class="control-label"></label>
                                <select asp-for="LineOfBusinessId" class="form-control" asp-items="ViewBag.LineOfBusinessId"></select>
                            </div>
                            <div class="form-group">
                                <label asp-for="InvestigationCaseStatusId" class="control-label"></label>
                                <select asp-for="InvestigationCaseStatusId" class="form-control"
                                        asp-items="ViewBag.RiskCaseStatusId"></select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Created" class="control-label"></label>
                                <input asp-for="Created" class="form-control" />
                                <span asp-validation-for="Created" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="card-footer text-right">
                            <a asp-action="Index" class="btn btn-secondary">
                                <i class="fa fa-window-close"></i>
                                Cancel
                            </a>
                            <button type="submit" class="btn btn-success">
                                <i class="fas fa-plus"></i> Create
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

risk.control.system/Views/InvestigationCase/Delete.cshtml
@model risk.control.system.Models.InvestigationCase

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Case</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LineOfBusiness)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LineOfBusiness.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InvestigationCaseStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InvestigationCaseStatus.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InvestigationId" />
            <div class="form-group">
                <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-window-close"></i> Cancel </a> &nbsp;
                <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button>
            </div>
    </form>
</div>

risk.control.system/Views/InvestigationCase/Details.cshtml
@model risk.control.system.Models.InvestigationCase

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Case</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LineOfBusiness)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LineOfBusiness.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InvestigationCaseStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InvestigationCaseStatus.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
</div>
    <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-window-close"></i> Cancel</a> &nbsp;
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.InvestigationId"><i class="fas fa-pen"></i> Edit</a>

risk.control.system/Views/InvestigationCase/Index.cshtml
@model List<risk.control.system.Models.InvestigationCase>

@{
    ViewData["Title"] = @Applicationsettings.INVESTIGATION_CLAIMS_CASE;
}
<section class="content pt-2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">@Applicationsettings.INVESTIGATION_CLAIMS_CASE</h3>
                    </div>
                    <form asp-action="index">
                        <div class="card-body dataTable-search-form">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <input autocomplete="off" name="searchString" type="text" class="form-control" placeholder="enter investigation case name or any detail">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 text-right">
                                    <button id="btnFilter" type="submit" class="btn btn-primary"><i class="fas fa-search"></i> @Applicationsettings.SEARCH</button>
                                    <a class="btn btn-success" asp-controller="InvestigationCase" asp-action="Create"><i class="fas fa-plus"></i> @Applicationsettings.CREATE</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card card-light">
                    <div class="card-body contained-width">
                        <form asp-action="Broadcast" id="checkboxes" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-12">
                                    @if (Model == null || Model.Count() == 0)
                                    {
                                        <caption>@Applicationsettings.NO_RECORDS_FOUND</caption>
                                    }
                                    else
                                    {
                                        <table class="table table-striped fixed-with-height">
                                            <thead>
                                                <tr>
                                                    <th><input type="checkbox" id="checkall" /></th>
                                                    <th>
                                                        @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm })
                                                    </th>
                                                    <th>
                                                        @Html.ActionLink("Description", "Index", new { sortOrder = ViewBag.NameSortParm })
                                                    </th>
                                                    <th>
                                                        @Html.ActionLink("Line of Business", "Index", new { sortOrder = ViewBag.NameSortParm })
                                                    </th>
                                                    <th>
                                                        @Html.ActionLink("Case status", "Index", new { sortOrder = ViewBag.NameSortParm })
                                                    </th>
                                                    <th>
                                                        @Html.ActionLink("Created", "Index", new { sortOrder = ViewBag.DateSortParm })
                                                    </th>
                                                    <th>Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)

                                                {
                                                    <tr>
                                                        <td>
                                                            <input name="cbxcase" type="checkbox" />
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Name)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Description)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.LineOfBusiness.Name)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.InvestigationCaseStatus.Name)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Created)
                                                        </td>
                                                        <td>
                                                            <a class="btn btn-xs btn-info" asp-action="Details" asp-route-id="@item.InvestigationId">
                                                                <i class="fa fa-search"></i> View
                                                            </a> &nbsp;
                                                            <a class="btn btn-xs btn-warning" asp-action="Edit" asp-route-id="@item.InvestigationId">
                                                                <i class="fas fa-pen"></i> Edit
                                                            </a> &nbsp;
                                                            <a class="btn btn-xs btn-danger" asp-action="Delete" asp-route-id="@item.InvestigationId">
                                                                <i class="fas fa-trash"></i> Delete
                                                            </a>
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    }
                                </div>
                            </div>
                            @if (Model != null && Model?.Count() > 0)
                            {
                                <div class="row">
                                    <div class="col-12">
                                        <div class="card-footer text-right">
                                            <a asp-action="Index" class="btn btn-secondary">
                                                <i class="fa fa-window-close"></i>
                                                @Applicationsettings.CANCEL
                                            </a>
                                            <button id="broadcast" disabled type="submit" class="btn btn-success">
                                                <i class="fa fa-paper-plane" aria-hidden="true"></i> @Applicationsettings.BROADCAST
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            }
                        </form>
                    </div>

                </div>
            </div>
            <br />
            @{
                var PageNumber = (int)@ViewBag.PageNumber;

                var PageSize = (int)@ViewBag.PageSize;

                var TotalPages = (int)@ViewBag.TotalPages;

                var ShowPrevious = (bool)@ViewBag.ShowPrevious;

                var ShowNext = (bool)@ViewBag.ShowNext;

                var ShowFirst = (bool)@ViewBag.ShowFirst;

                var ShowLast = (bool)@ViewBag.ShowLast;
            }
            <ul class="pagination">
                <li class="page-item @(!ShowFirst? "disabled":"")">
                    <a asp-page="/pagination" asp-route-CurrentPage="1" class="page-link">
                        <i class="fas fa-fast-backward"></i>
                    </a>
                </li>
                <li class="page-item @(!ShowPrevious? "disabled":"")">
                    <a asp-page="/pagination" asp-route-CurrentPage="@(PageNumber -1)" class="page-link">
                        <i class="fas fa-step-backward"></i>
                    </a>
                </li>
                <li class="page-item  @(!ShowNext? "disabled":"")">
                    <a asp-page="/pagination" asp-route-CurrentPage="@(PageNumber + 1)" class="page-link">
                        <i class="fas fa-step-forward"></i>
                    </a>
                </li>

                <li class="page-item  @(!ShowLast? "disabled":"")">
                    <a asp-page="/pagination" asp-route-CurrentPage="@TotalPages" class="page-link">
                        <i class="fas fa-fast-forward"></i>
                    </a>
                </li>
            </ul>

        </div>
    </div>
</section>